# Generated by Django 4.2.13 on 2024-05-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zerotierdevices',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='zerotierrequestaccess',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='zerotierdevices',
            name='tags',
            field=models.JSONField(default='', verbose_name=dict),
        ),
        migrations.AddField(
            model_name='zerotierrequestaccess',
            name='tags',
            field=models.JSONField(default='', verbose_name=dict),
        ),
    ]
