# Generated by Django 4.2.13 on 2024-05-26 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0002_remove_zerotierdevices_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerotierdevices',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='zerotierdevices',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
