# Generated by Django 4.2.13 on 2024-05-26 06:21

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0003_alter_zerotierdevices_last_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerotierdevices',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='zerotierdevices',
            name='last_update',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='last_update',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now),
        ),
    ]
