# Generated by Django 4.2.13 on 2024-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0005_alter_zerotierdevices_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerotierdevices',
            name='tags',
            field=models.JSONField(verbose_name=dict),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='tags',
            field=models.JSONField(verbose_name=dict),
        ),
    ]
