# Generated by Django 4.2.13 on 2024-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0006_alter_zerotierdevices_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerotierdevices',
            name='last_online',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='zerotierdevices',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='last_online',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='zerotierrequestaccess',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
    ]
